### PR TITLE
calendar warning only for rest.myria.cs...

### PR DESCRIPTION
**Pull request by radion**
Should the "Myria cluster is reserved" message show up if you're not connected to rest.myria.cs.washington.edu?

### CODE REVIEW

**Comment by dhalperi** [comment]
please update from master for the fix I put in #243

**Comment by radion** [comment]
So do we want to only filter out just localhost, regex the list of machines, use rest.myria..., or leave the code as it was? I'll update the code with the changes we want here.

**Comment by dhalperi** [comment]
Here's my calculus:

* current state of the world: developer using a private deployment sees a calendar warning anyway
    * Downside: fraudulent warning
    * Downside: to disable warning, developer has to figure out the right JS and disable
    * Upside: developers whose private deployments use the stars cluster will see the warning.

* Removing the check except for 'rest.cs.washington.edu' exactly:
    * Upside: no private deployments will see the warning
    * Downside: developers whose private deployments use the stars cluster will NOT see the warning.
    * Downside: **cluster reservations may be inadvertently violated through myria-web by our developers**

* Removing the check except for regex on `*.cs.washington.edu`:
    * similar to previous warning, does not solve either the false positive or false negative problem
        * false positive: my machine is `dhm.dyn.cs.washington.edu`...
        * false negative: e.g., deployment hosted from `sol`, not `*.cs.washington.edu`

* Adding an exception for specifically `localhost`
    * upside: most common "innocent dev / outsider dev" use case is probably people modifying `deployment.cfg.local`, so this would fix false positive in majority of cases.
    * downside: still may be some false positives
    * downside: false negatives, I guess, if someone ran myria-web from a cluster node.

I feel like the last one is optimal, but would hear other opinions.

**Comment by radion** [comment]
I agree, for now, we should go with the localhost option. That's the main reason I thought of this change.

The ideal solution, I think, is to create a set of reserved worker machines that the code checks against. But I don't know if that's a possibility.

**Pull request merged**
