### PR TITLE
Adding tabs to load statements

### PR DESCRIPTION
**Pull request by jortiz16**

### CODE REVIEW

**Comment by senderista** [comment]
These indents are spaces not tabs, right?

**Comment by jortiz16** [comment]
On my editor I have 1 tab = 2 spaces.  So I did 4 tabs on the csv line and then lined up the other attribute names with the first one.

**Comment by senderista** [comment]
Sorry, I'm still not clear. Do you mean your editor inserts two spaces when you hit tab, or that it displays a tab char as two spaces?

I just want to ensure that you added space chars not tab chars to the file, and I can't see that easily on github (although I could if I checked out the branch and fed the right incantations to `git diff`).

**Comment by jortiz16** [comment]
That's ok! yes, it inserts two spaces when I hit tab. In other words, I have the option: "indents using spaces" on.

**Pull request merged**
