### PR TITLE
Make sure tooltips are properly initialized. What happened is that you had to hover to initialize the tooltip and then hover again to see it.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
@BrandonHaynes How do I update the demo app?

**Comment by BrandonHaynes** [comment]
Easiest is to merge into master and I'll pull the changes on demo.

Harder is to get me a public key and I can arrange SSH access to demo.  Eventually the public keys need to be inserted into the cluster configuration so they're automatically created.

**Comment by domoritz** [comment]
Aren't we running myria-web on appengine? Also, can you review and merge this?

**Comment by BrandonHaynes** [comment]
Fix looks great.  Demo runs under the local development appengine; it's just like any other StarCluster instance.

**Comment by domoritz** [comment]
Ah, okay. Can you set them up in a way that we can see the branch and commit version? 

screen shot 2015-05-07 at 20 20 58

**Comment by BrandonHaynes** [comment]
Ah, that's why you sent over the `deploy.sh` note.  

I've manually updated the current demo cluster, but it won't survive a recycle.  A change to the StarCluster plugin is needed to automatically execute `deploy.sh` on startup.  See https://github.com/uwescience/myria-ec2/issues/12

**Pull request merged**
